### ISSUE TITLE
Update.me

### ISSUE THREAD

**Issue by GODLIKE5** [AJS-development/heroku#1]
This version of Ogar Ul is old if you go to ur url it says upgrade required and i dont know why but any gamemode i try it lags on heroku. But i see rainbowdemo.herokuapp.com and ogarunlimited.herokuapp.com and it dont lag. any way to update this or pass me the whole configs for any of the 2. Thxs

**Comment by Andrews54757** [comment]
Project is closed

**Comment by GODLIKE5** [comment]
Um anyway to get it back up or to update it myself? email me at fmelio1020@gmail.com. Thxs

**Comment by Andrews54757** [comment]
No. Busy making new version

**Comment by LegitSoulja** [comment]
@GODLIKE5 Register here http://forum.ogarul.io and you will get alerts in the future via email about ogarunlimited.
